FROM fedora:27
RUN dnf -y install mono-devel git
RUN dnf -y install nuget
RUN mozroots --import --sync
RUN cert-sync /etc/pki/tls/certs/ca-bundle.crt
VOLUME /src
WORKDIR /src
# Run  curl -f -k -L -o NuGet.Restore.targets http://bit.ly/nugetore and then xbuild NuGet.Restore.targets /t:Init
# now xbuild will work
