FROM fedora:27
RUN dnf -y install mono-devel git
RUN dnf -y install nuget
RUN mozroots --import --sync
RUN cert-sync /etc/pki/tls/certs/ca-bundle.crt
WORKDIR /src
RUN git clone https://github.com/secondsun/fehbot .
RUN  curl -f -k -L -o NuGet.Restore.targets http://bit.ly/nugetore 
RUN nuget restore
RUN xbuild
